name: Publish module version
# triggered by a dev updating the terraform module
# almost exclusively because the underlying cloudformation template has updated
# and we want to match version with that, which may or may not require a functionality change
# so there is currently a version mismatch
# dev needs to determine whether code changes are needed in module

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'The module to publish a new version of'
        type: string
        required: true
      version:
        description: 'The new version number to publish'
        type: string
        required: true
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pull out version number for that module
      - name: Overwrite module version numbers
        run: |
          echo 'Overwriting module versioning'
          sh $GITHUB_WORKSPACE/.github/scripts/version_overwrite.sh ${{ inputs.module }}/variables.tf

      # check if tag exists for that version
      - name: Check for version tag
        run: echo 'check version tag'

      # create tag and push
      - name: Create version tag
        run: echo 'create version tag'
